Fix ci

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -28,6 +28,11 @@ jobs:
       - name: Install Pipenv
         run: python -m pip install pipenv
       - name: Install denendencies
-        run: make installdeps && pipenv run which molecule
+        run: |
+          set -eux
+          # Sometimes fails to install packages for unknown reason
+          # so do this twice
+          make installdeps || make installdeps
+          pipenv run which molecule
       - name: Run molecule test
         run: make check
